### ISSUE TITLE
Create sensible API

### ISSUE THREAD

**Issue by omouse** [omouse/node-oauth-libre#1]
# Tasks
-   [ ] look at other oauth and oauth2 libraries for other languages and potentially emulate their APIs
-   [ ] create `future` module, completely licensed under GPL v3 or later; this is where new sensible api code will live so that we can be backwards-compatible until 1.0.0 when we switch to the sensible module completely
-   [x] [explore possible implementation of promises](https://github.com/ciaranj/node-oauth/issues/289), may make the API cleaner, or at least provide an alternative for people that prefer promises to callbacks
-   [ ] split credentials object into other objects:
  
  ``` js
  OAuthProvider = {
  
    baseSiteUrl: "http://",
    authorizePath: "...",
    accessTokenPath: "...",
    customHeaders: { /*...*/ }
  }
  
  OAuthClientCredentials = {
    clientId: "...",
    clientSecret: "..."
  }
  ```
-   [ ] change name of `getOAuthAccessToken()` to `token()`, add new method `refresh()`
  
  ``` js
  var client = new OAuthClient(provider, credentials);
  var refreshToken;
  
  client.getToken(function(err, token, _refreshToken) {
    refreshToken = _refreshToken;
    console.log(_refreshToken + ' = ' + refreshToken + ' = ' + client.refreshToken);
  });
  
  client.refresh(refreshToken, function(err, token, _refreshToken) {
  });
  
  client.refresh(function(err, token) {
    console.log(client.token);
    console.log(client.refreshToken);
  });
  ```
- [ ] potentially model [the other authorization flows that exist](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2)

**Comment by omouse** [comment]
alternatively we should provide api methods that include the step number? step1_auth, step2_access?

**Comment by caco0516** [comment]
@omouse So we add step#_ prefix to make this API more friendly ?

**Comment by omouse** [comment]
@caco0516 that's one option, not sure how useful it is (are there more than 2 steps? does refreshing the token count as a step?)

I think this needs more research, perhaps looking at the API for oauth libraries for Python, Ruby, C# and Java.

**Comment by omouse** [comment]
not sure if we need this / it's open for discussion, going to close the issue for now
